export const FETCH_PRODUCTS = "FETCH_PRODUCT";
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";

//for user login and registration.......
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_SIGNIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";