export const FETCH_PRODUCTS = "FETCH_PRODUCT";
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";